### PR TITLE
Merge https://github.com/vkostyukov/kotlin-sublime-package and update language definition

### PR DESCRIPTION
**Pull request by sommd**
Merged upstream repository for Kotlin.tmLanguage into this repo. Upstream should be able to be pulled using "git pull git@github.com:vkostyukov/kotlin-sublime-package master" (haven't tested this).

This repo should have been a fork of vkostyukov/kotlin-sublime-package in the first place. This is a way of fixing this without rebasing and rewriting history.

Doing this adds support for a bunch of new keywords and removes outdated keywords and file extensions.

Also fixed class/object/interface from upstream Kotlin.tmLanguage not working due to a possible bug in VS Code.

### CODE REVIEW

**Comment by sommd** [comment]
This looks like a lot of commits but really it's only the last 4. The rest are just pulled from https://github.com/vkostyukov/kotlin-sublime-package.

**Comment by rogersachan** [comment]
+1

**Comment by mathiasfrohlich** [comment]
Thanks again for the contribution.
Will preform some tests and then publish.

**Comment by mathiasfrohlich** [comment]
It is now Live
Thanks for the contribution

**Pull request closed without merging**
